# Generated by Django 5.2.1 on 2025-05-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='suscripcion_activa',
            field=models.BooleanField(default=False, verbose_name='Suscripción activa'),
        ),
    ]
